### ISSUE TITLE
Use ede-php-autoload package version for the dependency declaration

### ISSUE THREAD

**Issue by stevenremot** [xendk/ede-php-autoload-composer-installers#4]
In the Package-Requires declaration I can see ede-php-autoload is declared using a melpa version.

I just created the 1.0.0 version, and I think that's more interesting to use this one in the Package-Requires.

What do you think ?

**Comment by xendk** [comment]
Sure, I was planning on using the next stable release when it was available.

I'll get that fixed for the 0.1.0 (or should that be 1.0.0? Always the question) release.

**Comment by stevenremot** [comment]
Nice! Regarding tour package's version I'm not really good at versionningnso I won't be any help I think... I juste tend to let my packages un 0.* until I think it's mature enough to ne used by others...

**Comment by xendk** [comment]
Yeah, I better keep it at 0.x.y until I get the two other issues closed.
